### ISSUE TITLE
Wrong UTF-8 encoding

### ISSUE THREAD

**Issue by Developer113** [dumitrubogdanmihai/processing-web-data-with-xml-and-xslt#1]
Am download-at proiectul si am incercat sa reproduc exemplul din webinar, am ajuns in stadiul in care trebuia sa aplic stylesheet-ul pe xhtml-uri si am obtinut urmatoarea eroare: "Saxon-PE 9.9.1.7 Invalid byte 1 of 1-byte UTF-8 sequence".
Puteti sa ma ajutati cu depasirea acestei situatii?

Multumesc!
Serban Gligor

**Comment by dumitrubogdanmihai** [comment]
TLDR: Am fixat scrierea fisierlor sa se faca cu UTF-8 si am adaugat _XML Declaration_-ul in [commit-ul acesta](https://github.com/dumitrubogdanmihai/processing-web-data-with-xml-and-xslt/commit/8f84e38e8754b82fc8eda47626789c5d1107e7e6).


Fiecare fisier XML este scris cu un anumit encoding si doar cu acel encoding trebuie citit. Un encoding este o mapare de la un caracter ("a") la codul binar ("01100001" in cazul encoding-ul UTF-8) care este scris efectiv pe disc.

Atunci cand XML-ul este citit de pe disc, continutul binar este "convertit" la caractere. Acest lucru este facut pe baza encoding-ului. 
Standardul XML stipuleaza ca encoding-ul este implicit [UTF-8/UTF-16](https://www.oreilly.com/library/view/xml-hacks/0596007116/ch01s02.html) sau explicit declarat in _XML Declaration_.

Presupun ca problema vine de la faptului ca scrierea documentelor pe disc a fost facuta cu encoding-ul platformei (care, in general, pe Linux este UTF-8 si pe Windows CP-1252) si ca acesta nu a fost declarat in _XML Declaration_. Astfel Saxon-ul ajungand sa citeasca cu encoding-ul UTF-8 fisiere scrise cu encoding-ul CP-1252.

Merci pentru sesizare,
Bogdan
